# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  encoding: utf8
  database: speaksy_development
  template: template0

test: &TEST
  <<: *default
  encoding: utf8
  database: speaksy_test
  template: template0

production:
  <<: *default
  encoding: utf8
  database: speaksy_production
  template: template0